# Generated by Django 2.2.5 on 2019-10-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191022_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='image',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_ocorrencia',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='nome',
            field=models.CharField(blank='True', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='telefone',
            field=models.DecimalField(blank='True', decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
