# Generated by Django 2.2.5 on 2019-10-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20191025_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='telefone',
            field=models.CharField(blank='True', max_length=20),
        ),
    ]
