# Generated by Django 2.2.5 on 2019-10-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20191025_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='image',
            field=models.ImageField(upload_to='tasks.images', verbose_name='Imagem'),
        ),
    ]
