# Generated by Django 2.2.5 on 2019-10-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20191026_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/images', verbose_name='Imagem'),
        ),
    ]
