# Generated by Django 2.2.5 on 2019-11-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20191102_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='cep',
            field=models.CharField(blank='True', max_length=30, verbose_name='CEP'),
        ),
    ]
