# Generated by Django 2.2.5 on 2019-11-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20191102_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tmp', verbose_name='Imagem'),
        ),
    ]
